# Site settings
title: Shaun Can Code
email: shaunkelly@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Shaun Kelly. This is my code portfolio.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://6stringbeliever.github.io/" # the base hostname & protocol for your site
twitter_username: 6stringbeliever
github_username:  6stringbeliever

# Build settings
markdown: kramdown
